# Generated by Django 4.2.30 on 2026-06-01 19:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('youth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('MISSED_SESSIONS', 'Séances manquées'), ('PLAN_EXPIRING', 'Plan expirant'), ('UNAUTHORIZED_ACCESS', 'Accès non autorisé'), ('ASSESSMENT_REQUIRED', 'Évaluation requise'), ('INACTIVITY', 'Inactivité'), ('MENTOR_RECOMMENDATION', 'Recommandation mentor')], max_length=30, verbose_name="Type d'alerte")),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], default='MEDIUM', max_length=10, verbose_name='Sévérité')),
                ('message', models.TextField(verbose_name='Message')),
                ('triggered_by', models.CharField(default='system', help_text='"system" ou email de l\'utilisateur', max_length=200, verbose_name='Déclenché par')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='youth.youthprofile', verbose_name='Jeune')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-created_at'],
            },
        ),
    ]
