# Generated by Django 4.2.30 on 2026-06-01 19:31

import apps.youth.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouthProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Genre')),
                ('governorate', models.CharField(choices=[('TUNIS', 'Tunis'), ('ARIANA', 'Ariana'), ('BEN_AROUS', 'Ben Arous'), ('MANOUBA', 'Manouba'), ('NABEUL', 'Nabeul'), ('ZAGHOUAN', 'Zaghouan'), ('BIZERTE', 'Bizerte'), ('BEJA', 'Béja'), ('JENDOUBA', 'Jendouba'), ('KEF', 'Le Kef'), ('SILIANA', 'Siliana'), ('SOUSSE', 'Sousse'), ('MONASTIR', 'Monastir'), ('MAHDIA', 'Mahdia'), ('SFAX', 'Sfax'), ('KAIROUAN', 'Kairouan'), ('KASSERINE', 'Kasserine'), ('SIDI_BOUZID', 'Sidi Bouzid'), ('GABES', 'Gabès'), ('MEDNINE', 'Médenine'), ('TATAOUINE', 'Tataouine'), ('GAFSA', 'Gafsa'), ('TOZEUR', 'Tozeur'), ('KEBILI', 'Kébili')], max_length=20, verbose_name='Gouvernorat')),
                ('education_level', models.CharField(choices=[('COLLEGE', 'Collège'), ('LYCEE', 'Lycée'), ('BAC', 'Baccalauréat'), ('BAC_PLUS_2', 'Bac+2'), ('LICENCE', 'Licence'), ('MASTER', 'Master'), ('DROPOUT', 'Décrochage scolaire')], max_length=20, verbose_name="Niveau d'éducation")),
                ('current_school_or_institution', models.CharField(blank=True, max_length=200, verbose_name='École / Institution actuelle')),
                ('status', models.CharField(choices=[('REGISTERED', 'Inscrit'), ('ASSESSED', 'Évalué'), ('PLAN_ACTIVE', 'Plan actif'), ('IN_MENTORSHIP', 'En mentorat'), ('COMPLETED', 'Parcours complété'), ('INACTIVE', 'Inactif')], default='REGISTERED', max_length=20, verbose_name='Statut')),
                ('readiness_score', models.IntegerField(blank=True, null=True, verbose_name='Score de préparation')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_counselor', models.ForeignKey(blank=True, limit_choices_to=apps.youth.models._counselor_limit, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_youth', to=settings.AUTH_USER_MODEL, verbose_name='Conseiller assigné')),
                ('assigned_mentor', models.ForeignKey(blank=True, limit_choices_to=apps.youth.models._mentor_limit, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_youth', to=settings.AUTH_USER_MODEL, verbose_name='Mentor assigné')),
                ('interests', models.ManyToManyField(blank=True, related_name='interested_youth', to='careers.careersector', verbose_name="Secteurs d'intérêt")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='youth_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil jeune',
                'verbose_name_plural': 'Profils jeunes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterestAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_date', models.DateField(verbose_name="Date d'évaluation")),
                ('responses', models.JSONField(default=dict, help_text='Dictionnaire question → réponse', verbose_name='Réponses')),
                ('score_breakdown', models.JSONField(default=dict, verbose_name='Détail du score')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('COMPLETED', 'Complété')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conducted_by', models.ForeignKey(limit_choices_to=apps.youth.models._counselor_limit, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Conduit par (conseiller)')),
                ('recommended_sectors', models.ManyToManyField(blank=True, related_name='recommended_in_assessments', to='careers.careersector', verbose_name='Secteurs recommandés')),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='youth.youthprofile', verbose_name='Jeune')),
            ],
            options={
                'verbose_name': 'Évaluation des intérêts',
                'verbose_name_plural': 'Évaluations des intérêts',
                'ordering': ['-assessment_date'],
            },
        ),
    ]
