# Generated by Django 4.2.30 on 2026-06-01 18:17

import cases.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'Nouveau'), ('ASSESSMENT', 'Évaluation'), ('INTERVENTION', 'Intervention'), ('FOLLOW_UP', 'Suivi'), ('CLOSED', 'Clôturé')], default='NEW', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absences', models.PositiveIntegerField(default=0)),
                ('grade_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('missed_sessions', models.PositiveIntegerField(default=0)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=64, unique=True, validators=[cases.models.validate_student_code])),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('age', models.PositiveSmallIntegerField(validators=[cases.models.validate_age])),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('X', 'Autre')], max_length=1)),
                ('region', models.CharField(choices=[('TUNIS', 'Tunis'), ('SFAX', 'Sfax'), ('SOUSSE', 'Sousse'), ('MONASTIR', 'Monastir'), ('BIZERTE', 'Bizerte'), ('GABES', 'Gabès'), ('AUTRE', 'Autre')], default='AUTRE', max_length=32)),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('grade_level', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='RiskThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(choices=[('ABSENCES', 'Absences'), ('GRADE_AVG', 'Moyenne des notes'), ('MISSED_SESSIONS', 'Séances manquées')], max_length=32)),
                ('operator', models.CharField(choices=[('GTE', '>= (GTE)'), ('LTE', '<= (LTE)'), ('GT', '> (GT)'), ('LT', '< (LT)')], max_length=8)),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planifié'), ('ATTENDED', 'Présent'), ('MISSED', 'Manqué'), ('CANCELLED', 'Annulé')], default='SCHEDULED', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='cases.student')),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32, null=True)),
                ('to_status', models.CharField(max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cases.student'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('critical', 'Critique')], default='info', max_length=16)),
                ('message', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cases.case')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cases.student')),
                ('triggered_by_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.riskthreshold')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
