# Generated by Django 4.2.30 on 2026-06-01 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        ('youth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField(verbose_name='Date de la séance')),
                ('session_type', models.CharField(choices=[('DISCOVERY', 'Découverte'), ('SKILLS_REVIEW', 'Revue des compétences'), ('CV_REVIEW', 'Revue de CV'), ('MOCK_INTERVIEW', 'Entretien simulé'), ('FOLLOW_UP', 'Suivi')], max_length=20, verbose_name='Type de séance')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planifiée'), ('COMPLETED', 'Complétée'), ('MISSED', 'Manquée'), ('CANCELLED', 'Annulée')], default='SCHEDULED', max_length=15, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recommandations')),
                ('counselor_notified', models.BooleanField(default=False, verbose_name='Conseiller notifié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'MENTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Mentor')),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_sessions', to='youth.youthprofile', verbose_name='Jeune')),
            ],
            options={
                'verbose_name': 'Séance de mentorat',
                'verbose_name_plural': 'Séances de mentorat',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Entreprise')),
                ('years_of_experience', models.IntegerField(verbose_name="Années d'expérience")),
                ('bio', models.TextField(verbose_name='Biographie')),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('BUSY', 'Occupé'), ('UNAVAILABLE', 'Indisponible')], default='AVAILABLE', max_length=15, verbose_name='Disponibilité')),
                ('max_youth_capacity', models.IntegerField(default=3, verbose_name='Capacité maximale')),
                ('current_youth_count', models.IntegerField(default=0, verbose_name='Nombre de jeunes actuels')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentors', to='careers.careersector', verbose_name="Secteur d'expertise")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil mentor',
                'verbose_name_plural': 'Profils mentors',
                'ordering': ['user__last_name'],
            },
        ),
    ]
