# Generated by Django 4.2.30 on 2026-06-01 19:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du secteur')),
                ('description', models.TextField(verbose_name='Description')),
                ('demand_level', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], default='MEDIUM', max_length=10, verbose_name='Niveau de demande')),
                ('average_salary_range', models.CharField(blank=True, max_length=100, verbose_name='Fourchette salariale moyenne')),
                ('required_education_level', models.CharField(blank=True, max_length=100, verbose_name="Niveau d'éducation requis")),
                ('relevance_weight', models.IntegerField(default=2, help_text='Utilisé dans le calcul du score de préparation (1=faible, 3=élevé)', verbose_name='Poids de pertinence (1-3)')),
            ],
            options={
                'verbose_name': 'Secteur professionnel',
                'verbose_name_plural': 'Secteurs professionnels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Intitulé du métier')),
                ('description', models.TextField(verbose_name='Description')),
                ('required_skills', models.TextField(verbose_name='Compétences requises')),
                ('training_duration_months', models.IntegerField(verbose_name='Durée de formation (mois)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_paths', to='careers.careersector', verbose_name='Secteur')),
            ],
            options={
                'verbose_name': 'Parcours professionnel',
                'verbose_name_plural': 'Parcours professionnels',
                'ordering': ['sector', 'title'],
            },
        ),
    ]
