# Generated by Django 4.2.30 on 2026-06-01 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        ('youth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('VALIDATED', 'Validé'), ('ACTIVE', 'Actif'), ('COMPLETED', 'Complété'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=15, verbose_name='Statut')),
                ('objectives', models.TextField(verbose_name='Objectifs')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('milestones', models.JSONField(default=list, help_text='Liste d\'objets: [{"title": "...", "due_date": "YYYY-MM-DD", "done": false}]', verbose_name='Jalons')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'COUNSELOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='Créé par (conseiller)')),
                ('target_career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to='careers.careerpath', verbose_name='Parcours cible')),
                ('target_sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to='careers.careersector', verbose_name='Secteur cible')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_plans', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='youth.youthprofile', verbose_name='Jeune')),
            ],
            options={
                'verbose_name': "Plan d'action",
                'verbose_name_plural': "Plans d'action",
                'ordering': ['-created_at'],
            },
        ),
    ]
